source "https://rubygems.org"

# gem "jekyll"
# gem "jekyll-theme-so-simple-libre", :git => "https://github.com/anandtrex/so-simple-libre-theme.git", :branch => "master"
gem "github-pages", group: :jekyll_plugins

gem "tzinfo-data"
gem "wdm", "~> 0.1.0" if Gem.win_platform?

# If you have any plugins, put them here!
# group :jekyll_plugins do
#   gem "jekyll-paginate"
#   gem "jekyll-sitemap"
#   gem "jekyll-gist"
#   gem "jekyll-feed"
#   gem "jemoji"
#   gem "jekyll-redirect-from"
# end
